package ru.bormoshka.tstocks.DAO.entities;
// Generated Nov 21, 2013 2:12:48 AM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * LocationType generated by hbm2java
 */
@Entity
@Table(name = "Address")
public class Address extends AbstractEntity  {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "city", length = 45)
	private String city = "";

	@Column(name = "district", length = 45)
	private String district = "";

	@Column(name = "street", length = 120)
	private String street = "";

	public Address(String city, String district, String street) {
		this.city = city;
		this.district = district;
		this.street = street;
	}

	public Address() {
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getCity() {
		return city;
	}

	public void setCity(String city) {
		this.city = city;
	}

	public String getDistrict() {
		return district;
	}

	public void setDistrict(String district) {
		this.district = district;
	}

	public String getStreet() {
		return street;
	}

	public void setStreet(String street) {
		this.street = street;
	}
	
	public String getFullAddress() {
		return city + ", " + district + ", " + street;
	}

}
