package ru.bormoshka.tstocks.DAO.entities;
// Generated Nov 23, 2013 3:05:27 PM by Hibernate Tools 3.6.0

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.Table;

/**
 * Composite generated by hbm2java
 */
@Entity
@Table(name = "Composite")
public class Composite extends AbstractEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "location_id", nullable = false, referencedColumnName = "id")
	private Location location;

	@Column(name = "is_supplied", nullable = false)
	private boolean isSupplied;

	@Column(name = "inventory_number", nullable = false)
	private String inventoryNumber;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "composite_type_id", nullable = false, referencedColumnName = "id")
	private CompositeType compositeType;

	public Composite() {
	}

	public Composite(Location location, boolean isSupplied, CompositeType compositeType, String inventoryNumber) {
		this.location = location;
		this.isSupplied = isSupplied;
		this.compositeType = compositeType;
		this.inventoryNumber = inventoryNumber;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Location getLocation() {
		return location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	

	public boolean isIsSupplied() {
		return this.isSupplied;
	}

	public void setIsSupplied(boolean isSupplied) {
		this.isSupplied = isSupplied;
	}

	public CompositeType getCompositeType() {
		return compositeType;
	}

	public void setCompositeType(CompositeType compositeType) {
		this.compositeType = compositeType;
	}

	public String getInventoryNumber() {
		return this.inventoryNumber;
	}

	public void setInventoryNumber(String inventoryNumber) {
		this.inventoryNumber = inventoryNumber;
	}

}
