package ru.bormoshka.tstocks.DAO.entities;
// Generated Nov 21, 2013 2:12:48 AM by Hibernate Tools 3.6.0

import com.vaadin.data.util.BeanItem;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;

/**
 * Location generated by hbm2java
 */
@Entity
@Table(name = "Location")
public class Location extends AbstractEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "name", nullable = false, length = 512)
	private String name;

	@Column(name = "address", nullable = false)
	private long address;

	@Column(name = "room", nullable = false, length = 45)
	private String room;

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "location")
	private Set<Unit> units = new HashSet<Unit>(0);

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "location_type_id", referencedColumnName = "id")
	private LocationType type;

	public Location() {
	}

	public Location(String name, long address, String room, LocationType type) {
		this.name = name;
		this.address = address;
		this.room = room;
		this.type = type;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public long getAddress() {
		return this.address;
	}

	public void setAddress(long address) {
		this.address = address;
	}

	public String getRoom() {
		return this.room;
	}

	public void setRoom(String room) {
		this.room = room;
	}

	public LocationType getType() {
		return type;
	}

	public void setType(LocationType type) {
		this.type = type;
	}

	public Set<Unit> getUnits() {
		return units;
	}

	public void setUnits(Set<Unit> units) {
		this.units = units;
	}

}
