package ru.bormoshka.tstocks.DAO.entities;
// Generated Nov 21, 2013 2:12:48 AM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "Transaction", catalog = "inventory")
public class TransactionUnit extends AbstractEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "unit_id", nullable = false)
	private long unitId;

	@Column(name = "comment", length = 512)
	private String comment;

	@Column(name = "operation", nullable = false, length = 512)
	private String operation;

	@Temporal(TemporalType.DATE)
	@Column(name = "create_time", length = 10)
	private Date createTime = new Date();

	public TransactionUnit() {
	}

	public TransactionUnit(long unitId, String operation) {
		this.unitId = unitId;
		this.operation = operation;
	}

	public TransactionUnit(long unitId, String comment, String operation) {
		this.unitId = unitId;
		this.comment = comment;
		this.operation = operation;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public long getUnitId() {
		return this.unitId;
	}

	public void setUnitId(long unitId) {
		this.unitId = unitId;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}
	
}
