package ru.bormoshka.tstocks.DAO.entities;
// Generated Nov 21, 2013 2:12:48 AM by Hibernate Tools 3.6.0

import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;

/**
 * Transaction generated by hbm2java
 */
@Entity
@Table(name = "Transaction", catalog = "inventory")
public class TransactionComposite extends AbstractEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Column(name = "composite_id", nullable = false)
	private long compositeId;

	@Column(name = "comment", length = 512)
	private String comment;

	@Column(name = "operation", nullable = false, length = 512)
	private String operation;

	@Temporal(TemporalType.DATE)
	@Column(name = "create_time", length = 10)
	private Date createTime = new Date();

	public TransactionComposite() {
	}

	public TransactionComposite(long compositeId, String operation) {
		this.compositeId = compositeId;
		this.operation = operation;
	}

	public TransactionComposite(long compositeId, String comment, String operation) {
		this.compositeId = compositeId;
		this.comment = comment;
		this.operation = operation;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getComment() {
		return this.comment;
	}

	public void setComment(String comment) {
		this.comment = comment;
	}

	public String getOperation() {
		return this.operation;
	}

	public void setOperation(String operation) {
		this.operation = operation;
	}

	public Date getCreateTime() {
		return this.createTime;
	}

	public void setCreateTime(Date createTime) {
		this.createTime = createTime;
	}

	public long getCompositeId() {
		return compositeId;
	}

	public void setCompositeId(long compositeId) {
		this.compositeId = compositeId;
	}
	
}
