package ru.bormoshka.tstocks.DAO.entities;
// Generated Nov 21, 2013 2:12:48 AM by Hibernate Tools 3.6.0

import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.CascadeType;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import static javax.persistence.GenerationType.IDENTITY;
import javax.persistence.Id;
import javax.persistence.JoinColumn;
import javax.persistence.ManyToOne;
import javax.persistence.OneToMany;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import org.hibernate.annotations.Fetch;
import org.hibernate.annotations.FetchMode;

/**
 * Unit generated by hbm2java
 */
@Entity(name = "Unit")
@Table(name = "Unit")
public class Unit extends AbstractEntity implements java.io.Serializable {

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "id", unique = true, nullable = false)
	private Long id;

	@Temporal(TemporalType.DATE)
	@Column(name = "date_begin", nullable = false, length = 10)
	private Date dateBegin = new Date();

	@Temporal(TemporalType.DATE)
	@Column(name = "date_end", length = 10)
	private Date dateEnd;

	@Column(name = "name", nullable = false, length = 512)
	private String name;

	@Column(name = "status", nullable = false)
	private Status status;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "location_id", nullable = false, referencedColumnName = "id")
	private Location location;

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "unit_type_id", nullable = false, referencedColumnName = "id")
	private UnitType unitType;

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER)
	@Fetch(FetchMode.JOIN)
	@JoinColumn(name = "unit_id")
	private Set<UnitPropertyValue> propertyValues = new HashSet<UnitPropertyValue>(0);

	public boolean validate() {
		if (name == null || name.equals("") || name.length() > 512) {
			return false;
		}
		if (location == null || location.getName() == null || location.getType() == null) {
			return false;
		}
		if (status == null) {
			return false;
		}
		if (unitType == null) {
			return false;
		}
		return true;
	}

	public Unit() {
	}

	public Unit(Date dateBegin, Date dateEnd, String name, Status status, Location location, UnitType unitType) {
		this.dateBegin = dateBegin;
		this.dateEnd = dateEnd;
		this.name = name;
		this.status = status;
		this.location = location;
		this.unitType = unitType;
	}

	public Unit(Long id, Date dateBegin, Date dateEnd, String name, Status status, Location location, UnitType unitType) {
		this.id = id;
		this.dateBegin = dateBegin;
		this.dateEnd = dateEnd;
		this.name = name;
		this.status = status;
		this.location = location;
		this.unitType = unitType;
	}

	public Long getId() {
		return this.id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public Date getDateBegin() {
		return this.dateBegin;
	}

	public void setDateBegin(Date dateBegin) {
		this.dateBegin = dateBegin;
	}

	public Date getDateEnd() {
		return this.dateEnd;
	}

	public void setDateEnd(Date dateEnd) {
		this.dateEnd = dateEnd;
	}

	public String getName() {
		return this.name;
	}

	public void setName(String name) {
		this.name = name;
	}

	public Status getStatus() {
		return this.status;
	}

	public void setStatus(Status status) {
		this.status = status;
	}

	public UnitType getUnitType() {
		return unitType;
	}

	public void setUnitType(UnitType unitType) {
		this.unitType = unitType;
	}

	public Location getLocation() {
		return location;
	}

	public void setLocation(Location location) {
		this.location = location;
	}

	public Set<UnitPropertyValue> getPropertyValues() {
		return propertyValues;
	}

	public void setPropertyValues(Set<UnitPropertyValue> propertyValues) {
		this.propertyValues = propertyValues;
	}
	
}
